
// THIS FILE IS AUTOGENERATED WHEN PAGES ARE UPDATED
import { lazy } from "react";
import { RouteObject } from "react-router-dom";


import { UserGuard } from "app";


import { StackHandlerRoutes, LoginRedirect } from "app/auth";


const App = lazy(() => import("./pages/App.tsx"));
const CreateOrder = lazy(() => import("./pages/CreateOrder.tsx"));

export const userRoutes: RouteObject[] = [

	{ path: "/auth/redirect", element: <LoginRedirect />},
	{ path: "/auth/*", element: <StackHandlerRoutes />},
	{ path: "/", element: <App />},
	{ path: "/create-order", element: <UserGuard><CreateOrder /></UserGuard>},
	{ path: "/createorder", element: <UserGuard><CreateOrder /></UserGuard>},

];
